import { RON_WEASLEY_IDENTITY } from '@/lib/hermes-boundaries'

export type AgentInterfaceStatus = 'live' | 'partial' | 'blocked' | 'not_installed'

export type AgentLocalInterface = {
  id: string
  name: string
  service_process: string
  local_bind_address: string
  local_port: string
  local_url: string | null
  tailnet_url: string | null
  owner_tunnel_url?: string | null
  mission_control_route: string
  mission_control_ui?: string | null
  owner_login_required: boolean
  public_exposure: 'no'
  status: AgentInterfaceStatus
  exact_blocker: string
  next_action: string
  configurable_tools: string[]
}

export const AGENT_LOCAL_INTERFACE_DISCOVERY = {
  generated_at: '2026-05-13T11:15:00-04:00',
  discovery_scope: 'read-only service, listener, container, Tailnet, and HTTP status probes',
  server_host: 'srv1568353',
  server_tailnet_ip: '100.116.35.95',
  owner_laptop_tailnet_ip: '100.108.96.80',
  no_secrets_read: true,
  no_env_values_read: true,
  public_exposure_created: false,
}

export const AGENT_LOCAL_INTERFACES: AgentLocalInterface[] = [
  {
    id: 'agent-zero',
    name: 'Agent Zero (Jarvis)',
    service_process: 'agent-zero Docker container',
    local_bind_address: '100.116.35.95',
    local_port: '50080 -> container:80',
    local_url: null,
    tailnet_url: 'http://100.116.35.95:50080/',
    mission_control_route: '/api/bridge/agent-zero/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'owner_hard_stops_only_remaining · Jarvis has an active owner Bridge Session and certified exact-scope Mission Control execution adapters. Raw secrets, .env edits, public exposure, broad connector execution, and credential injection remain hard stops.',
    next_action: 'Continue Jarvis Full GO adapter expansion through exact-scope routes with audit and rollback. Add credentials only through the owner secret path.',
    configurable_tools: ['commander status', 'protected request review', 'Bridge-gated actions'],
  },
  {
    id: 'hermes',
    name: RON_WEASLEY_IDENTITY.canonical_name,
    service_process: 'Ron Weasley WebUI loopback service + Mission Control Nuclear Dispatcher control plane',
    local_bind_address: '127.0.0.1',
    local_port: '8787',
    local_url: 'http://127.0.0.1:8787/',
    tailnet_url: null,
    mission_control_route: '/api/bridge/hermes/webui/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'jarvis_signed_exact_scope_delegation_required · hermes_webui_service_not_running_if_8787_unreachable · Ron Weasley has a direct Mission Control/Gateway line with full ecosystem visibility, Jarvis command-registry parity, and a loopback WebUI surface. Writes and executions require a Jarvis-signed exact-scope delegation packet.',
    next_action: 'Open http://127.0.0.1:8787/ for the standalone Ron Weasley WebUI when running. Use legacy /api/bridge/hermes/full-access/status, /api/bridge/hermes/system-command-registry, and /api/bridge/hermes/execute aliases for Gateway delegated parity.',
    configurable_tools: ['Ron Weasley WebUI', 'WebUI health', 'direct line status', 'full-access status', 'system command registry', 'delegated execute', 'readiness', 'capability map', 'authority map', 'brain map', 'tool map', 'skill drafts', 'workflow drafts', 'dispatch plans'],
  },
  {
    id: 'pi',
    name: 'PI Dispatcher',
    service_process: 'Mission Control dispatcher contract',
    local_bind_address: 'Mission Control',
    local_port: '3337',
    local_url: 'http://127.0.0.1:3337/gateway/agent-hub/pi/config',
    tailnet_url: 'http://100.116.35.95:3337/gateway/agent-hub/pi/config',
    mission_control_route: '/api/bridge/pi/status',
    mission_control_ui: '/gateway/agent-hub/pi/config',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'protected_execution_requires_owner_scope · PI can inspect Gateway inventory and open the owner UI. Writes and protected actions remain gated.',
    next_action: 'Open Pi through /gateway/agent-hub/pi/config. Use PI for route recommendations and inventory checks unless a separate exact-scope approval exists.',
    configurable_tools: ['provider registry read', 'capability matrix read', 'MCP registry read', 'agent roster read', 'Bridge readiness read', 'skills/tools inventory read', 'route recommendations'],
  },
  {
    id: 'spaceagent',
    name: 'SpaceAgent',
    service_process: 'Mission Control SpaceAgent contract; Playwright MCP local service',
    local_bind_address: 'Mission Control authenticated Gateway + 127.0.0.1 Playwright MCP tool',
    local_port: 'Gateway-brokered; Playwright MCP 8931 local-only',
    local_url: 'http://127.0.0.1:3337/gateway/agent-hub/spaceagent/config',
    tailnet_url: 'http://100.116.35.95:3337/gateway/agent-hub/spaceagent/config',
    mission_control_route: '/api/bridge/spaceagent/status',
    mission_control_ui: '/gateway/agent-hub/spaceagent/config',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'firecrawl_credential_required · firecrawl_backend_adapter_not_configured · youtube_transcript_ready_via_/api/youtube/transcript · interactive_browser_actions_require_bridge_session. Playwright MCP is server-local only.',
    next_action: 'Open SpaceAgent through /gateway/agent-hub/spaceagent/config. Use the owner UI for research status; Firecrawl, YouTube, and browser actions remain Gateway-gated tools.',
    configurable_tools: ['SpaceAgent direct-line trace', 'capability map', 'readiness', 'Brain status', 'tool map', 'certification proof', 'Playwright MCP read-only status', 'Browser Evidence Packet', 'Research Packet', 'Firecrawl readiness', 'YouTube transcript readiness'],
  },
  {
    id: 'paperclip',
    name: 'Paperclip',
    service_process: 'paperclip-lab dev runner (node/tsx)',
    local_bind_address: '100.116.35.95',
    local_port: '3100',
    local_url: 'http://127.0.0.1:3337/gateway/agent-hub/paperclip/ui',
    tailnet_url: 'http://100.116.35.95:3100/ECO/dashboard',
    mission_control_route: '/api/bridge/paperclip/status',
    mission_control_ui: '/gateway/agent-hub/paperclip/ui',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'paperclip_writes_bridge_gated · Owner-accessible company is E copier Solutions (ECO). To Knowledge Gateway (TOK) still needs owner membership repair before routing owner work there.',
    next_action: 'Use the ECO Paperclip dashboard for live owner reads. Keep real task creation Bridge-gated; repair TOK membership only if that legacy company must remain active.',
    configurable_tools: ['company dashboard', 'agent roster', 'task queue', 'issues/proposals'],
  },
  {
    id: 'openclaw-plus',
    name: 'OpenClaw+',
    service_process: 'openclaw-gateway.service',
    local_bind_address: '127.0.0.1',
    local_port: '18789, 18791',
    local_url: 'http://127.0.0.1:18789/',
    tailnet_url: null,
    owner_tunnel_url: 'http://127.0.0.1:18789/',
    mission_control_route: '/api/openclaw-plus/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'openclaw_doctor_runtime_not_reachable · Direct server-local URL is not public. Owner access is currently through the existing SSH/Tailnet tunnel to localhost:18789 on the owner laptop.',
    next_action: 'Keep OpenClaw+ tunnel-only or add an authenticated Mission Control proxy; do not expose the server-local gateway publicly.',
    configurable_tools: ['runtime doctor', 'skill registry', 'mini-agent runtime'],
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    service_process: 'playwright-mcp.service',
    local_bind_address: '127.0.0.1',
    local_port: '8931',
    local_url: 'http://127.0.0.1:8931/sse',
    tailnet_url: null,
    mission_control_route: '/api/bridge/space-agent/playwright-mcp/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'Endpoint is local-only by design; public exposure is not allowed.',
    next_action: 'Use Mission Control/SpaceAgent as the owner-facing control surface; keep MCP endpoint bound to loopback.',
    configurable_tools: ['browser automation', 'SSE MCP transport', 'evidence capture'],
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    service_process: 'No Firecrawl backend credential/adapter proven',
    local_bind_address: 'none',
    local_port: 'none',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/firecrawl/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'blocked',
    exact_blocker: 'FIRECRAWL_API_KEY and backend adapter proof are missing; crawls remain disabled.',
    next_action: 'Add Firecrawl credential through the approved secret path, wire adapter proof, then keep crawl execution Bridge-gated.',
    configurable_tools: ['readiness', 'crawl request route', 'job status route'],
  },
  {
    id: 'youtube',
    name: 'YouTube transcript',
    service_process: 'Mission Control read-only transcript adapter',
    local_bind_address: 'Mission Control authenticated Gateway',
    local_port: 'Gateway-brokered',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/youtube/transcript',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'read_only_transcript_route_available · full_video_downloads_blocked · authenticated_youtube_actions_not_configured. YouTube is a Gateway tool for SpaceAgent research, not the SpaceAgent identity.',
    next_action: 'Use the read-only transcript route first and surface success/unavailable/fallback states through SpaceAgent. Keep full video downloads and authenticated YouTube actions blocked until exact-scope proof exists.',
    configurable_tools: ['read-only transcript route', 'fallback state', 'report integration'],
  },
  {
    id: 'gbrain',
    name: 'Gbrain',
    service_process: 'Mission Control Brain Sync brokered knowledge lane',
    local_bind_address: 'Mission Control authenticated Gateway',
    local_port: 'Gateway-brokered',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/bridge/gbrain/status',
    mission_control_ui: '/designer-mission-control/Mission%20Control.html?page=gbrain-sync',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'gbrain_sync_pipeline_not_certified · gbrain_mcp_client_not_configured · Brain Sync write/sync execution remains Jarvis-gated until exact-scope MCP/client proof exists.',
    next_action: 'Open Gbrain inside Brain Sync at /designer-mission-control/Mission%20Control.html?page=gbrain-sync. Keep Gbrain visible as a Brain Sync lane, not a separate fake UI.',
    configurable_tools: ['Brain Sync Gbrain panel', 'status', 'runtime proof', 'MCP readiness', 'sync certification', 'completion audit', 'tool map'],
  },
  {
    id: 'bridge-session',
    name: 'Bridge Session',
    service_process: 'Mission Control approval queue',
    local_bind_address: '127.0.0.1 / 100.116.35.95',
    local_port: '3337',
    local_url: 'http://127.0.0.1:3337/gateway/bridge-session',
    tailnet_url: 'http://100.116.35.95:3337/gateway/bridge-session',
    mission_control_route: '/api/bridge/approval-requests',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'Approval records can be created locally, but protected execution remains disabled until runner/audit/rollback proof is complete.',
    next_action: 'Use Bridge Session for scoped approval records only; do not execute protected actions until the runner is separately proven.',
    configurable_tools: ['approval requests', 'approve/deny records', 'audit export pending'],
  },
]

export const DELIVERY_CONNECTOR_INTERFACES = [
  { id: 'telegram', name: 'Telegram', mission_control_route: '/api/bridge/telegram-readiness', status: 'blocked', blocker: 'TELEGRAM_BOT_TOKEN and TELEGRAM_OWNER_CHAT_ID missing from approved secret path' },
  { id: 'agentmail', name: 'AgentMail', mission_control_route: '/api/bridge/agentmail-readiness', status: 'blocked', blocker: 'AGENTMAIL_API_KEY and allowed recipient list missing from approved secret path' },
  { id: 'google-drive', name: 'Google Drive', mission_control_route: '/api/bridge/google-drive-readiness', status: 'blocked', blocker: 'Google Drive OAuth and target folder proof missing' },
  { id: 'onedrive', name: 'OneDrive', mission_control_route: '/api/bridge/onedrive-readiness', status: 'blocked', blocker: 'Microsoft Graph OAuth and OneDrive target folder proof missing' },
] as const
