export type AgentInterfaceStatus = 'live' | 'partial' | 'blocked' | 'not_installed'

export type AgentLocalInterface = {
  id: string
  name: string
  service_process: string
  local_bind_address: string
  local_port: string
  local_url: string | null
  tailnet_url: string | null
  owner_tunnel_url?: string | null
  mission_control_route: string
  owner_login_required: boolean
  public_exposure: 'no'
  status: AgentInterfaceStatus
  exact_blocker: string
  next_action: string
  configurable_tools: string[]
}

export const AGENT_LOCAL_INTERFACE_DISCOVERY = {
  generated_at: '2026-05-13T11:15:00-04:00',
  discovery_scope: 'read-only service, listener, container, Tailnet, and HTTP status probes',
  server_host: 'srv1568353',
  server_tailnet_ip: '100.116.35.95',
  owner_laptop_tailnet_ip: '100.108.96.80',
  no_secrets_read: true,
  no_env_values_read: true,
  public_exposure_created: false,
}

export const AGENT_LOCAL_INTERFACES: AgentLocalInterface[] = [
  {
    id: 'agent-zero',
    name: 'Agent Zero',
    service_process: 'agent-zero Docker container',
    local_bind_address: '100.116.35.95',
    local_port: '50080 -> container:80',
    local_url: null,
    tailnet_url: 'http://100.116.35.95:50080/',
    mission_control_route: '/api/agent-zero/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'agent_zero_fd_exhaustion_guard_pending · Owner UI, /login, and /api/health are reachable after an Agent Zero container restart; long-term file descriptor exhaustion guard remains pending, and /health, /status, and /api/status are absent upstream routes.',
    next_action: 'Add an Agent Zero fd-leak guard/health monitor, keep absent upstream routes documented, and add approved credentials only through the secret path.',
    configurable_tools: ['commander status', 'protected request review', 'Bridge-gated actions'],
  },
  {
    id: 'hermes',
    name: 'Hermes',
    service_process: 'hermes-gateway.service',
    local_bind_address: '127.0.0.1',
    local_port: '3000',
    local_url: 'http://127.0.0.1:3000/',
    tailnet_url: null,
    mission_control_route: '/api/hermes/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'hermes_owner_proxy_not_wired · Hermes health is live on server-local /health, but root/chat/status routes require auth and no safe Tailnet/proxy UI route is exposed yet.',
    next_action: 'Expose a Mission Control authenticated Hermes config/status panel or approved launch proxy; keep direct server-local URL private.',
    configurable_tools: ['adapter status', 'test-chat status', 'skill/workflow builder settings', 'blocked/gated tools'],
  },
  {
    id: 'pi',
    name: 'Pi',
    service_process: 'No standalone Pi service found',
    local_bind_address: 'none',
    local_port: 'none',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/bridge/dispatcher/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'pi_runtime_session_not_proven · Pi exists only as Mission Control dispatcher/advisory contract; no CLI/RPC/local UI service was found.',
    next_action: 'Keep Pi advisory-only in Agent Hub; add runtime only after an approved service path exists.',
    configurable_tools: ['route recommendations', 'blocked route reasons', 'advisory review'],
  },
  {
    id: 'spaceagent',
    name: 'SpaceAgent',
    service_process: 'No standalone SpaceAgent service found; playwright-mcp.service is active',
    local_bind_address: '127.0.0.1',
    local_port: '8931',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/bridge/space-agent/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'no_standalone_spaceagent_ui · firecrawl_credential_required · firecrawl_backend_adapter_not_configured · youtube_transcript_connector_not_proven · Playwright MCP is active on server-local 127.0.0.1:8931 with /sse reachable, but it is intentionally local-only; no standalone SpaceAgent owner UI exists.',
    next_action: 'Keep Playwright MCP local-only and expose SpaceAgent status/config through Mission Control; Firecrawl and YouTube remain separately gated.',
    configurable_tools: ['Playwright MCP', 'Browser Evidence Packet', 'Research Packet', 'Firecrawl readiness', 'YouTube transcript readiness'],
  },
  {
    id: 'paperclip',
    name: 'Paperclip',
    service_process: 'paperclip-lab dev runner (node/tsx)',
    local_bind_address: '100.116.35.95',
    local_port: '3100',
    local_url: null,
    tailnet_url: 'http://100.116.35.95:3100/ECO/dashboard',
    mission_control_route: '/api/bridge/paperclip/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'paperclip_writes_bridge_gated · Owner-accessible company is E copier Solutions (ECO). To Knowledge Gateway (TOK) still needs owner membership repair before routing owner work there.',
    next_action: 'Use the ECO Paperclip dashboard for live owner reads. Keep real task creation Bridge-gated; repair TOK membership only if that legacy company must remain active.',
    configurable_tools: ['company dashboard', 'agent roster', 'task queue', 'issues/proposals'],
  },
  {
    id: 'openclaw-plus',
    name: 'OpenClaw+',
    service_process: 'openclaw-gateway.service',
    local_bind_address: '127.0.0.1',
    local_port: '18789, 18791',
    local_url: 'http://127.0.0.1:18789/',
    tailnet_url: null,
    owner_tunnel_url: 'http://127.0.0.1:18789/',
    mission_control_route: '/api/openclaw-plus/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'openclaw_doctor_runtime_not_reachable · Direct server-local URL is not public. Owner access is currently through the existing SSH/Tailnet tunnel to localhost:18789 on the owner laptop.',
    next_action: 'Keep OpenClaw+ tunnel-only or add an authenticated Mission Control proxy; do not expose the server-local gateway publicly.',
    configurable_tools: ['runtime doctor', 'skill registry', 'mini-agent runtime'],
  },
  {
    id: 'playwright-mcp',
    name: 'Playwright MCP',
    service_process: 'playwright-mcp.service',
    local_bind_address: '127.0.0.1',
    local_port: '8931',
    local_url: 'http://127.0.0.1:8931/sse',
    tailnet_url: null,
    mission_control_route: '/api/bridge/space-agent/playwright-mcp/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'live',
    exact_blocker: 'Endpoint is local-only by design; public exposure is not allowed.',
    next_action: 'Use Mission Control/SpaceAgent as the owner-facing control surface; keep MCP endpoint bound to loopback.',
    configurable_tools: ['browser automation', 'SSE MCP transport', 'evidence capture'],
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    service_process: 'No Firecrawl backend credential/adapter proven',
    local_bind_address: 'none',
    local_port: 'none',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/firecrawl/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'blocked',
    exact_blocker: 'FIRECRAWL_API_KEY and backend adapter proof are missing; crawls remain disabled.',
    next_action: 'Add Firecrawl credential through the approved secret path, wire adapter proof, then keep crawl execution Bridge-gated.',
    configurable_tools: ['readiness', 'crawl request route', 'job status route'],
  },
  {
    id: 'youtube',
    name: 'YouTube connector',
    service_process: 'No transcript connector service found',
    local_bind_address: 'none',
    local_port: 'none',
    local_url: null,
    tailnet_url: null,
    mission_control_route: '/api/bridge/space-agent/status',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'blocked',
    exact_blocker: 'YouTube transcript connector proof is missing; full-video downloads remain blocked.',
    next_action: 'Install/prove transcript connector and expose success/unavailable/fallback states through SpaceAgent.',
    configurable_tools: ['transcript read', 'fallback state', 'report integration'],
  },
  {
    id: 'bridge-session',
    name: 'Bridge Session',
    service_process: 'Mission Control approval queue',
    local_bind_address: '127.0.0.1 / 100.116.35.95',
    local_port: '3337',
    local_url: 'http://127.0.0.1:3337/gateway/bridge-session',
    tailnet_url: 'http://100.116.35.95:3337/gateway/bridge-session',
    mission_control_route: '/api/bridge/approval-requests',
    owner_login_required: true,
    public_exposure: 'no',
    status: 'partial',
    exact_blocker: 'Approval records can be created locally, but protected execution remains disabled until runner/audit/rollback proof is complete.',
    next_action: 'Use Bridge Session for scoped approval records only; do not execute protected actions until the runner is separately proven.',
    configurable_tools: ['approval requests', 'approve/deny records', 'audit export pending'],
  },
]

export const DELIVERY_CONNECTOR_INTERFACES = [
  { id: 'telegram', name: 'Telegram', mission_control_route: '/api/bridge/telegram-readiness', status: 'blocked', blocker: 'TELEGRAM_BOT_TOKEN and TELEGRAM_OWNER_CHAT_ID missing from approved secret path' },
  { id: 'agentmail', name: 'AgentMail', mission_control_route: '/api/bridge/agentmail-readiness', status: 'blocked', blocker: 'AGENTMAIL_API_KEY and allowed recipient list missing from approved secret path' },
  { id: 'google-drive', name: 'Google Drive', mission_control_route: '/api/bridge/google-drive-readiness', status: 'blocked', blocker: 'Google Drive OAuth and target folder proof missing' },
  { id: 'onedrive', name: 'OneDrive', mission_control_route: '/api/bridge/onedrive-readiness', status: 'blocked', blocker: 'Microsoft Graph OAuth and OneDrive target folder proof missing' },
] as const
