export const bridgeProviders = [
  {
    id: 'agent-zero',
    label: 'Agent Zero (Jarvis)',
    state: 'CREDENTIAL_GATED',
    blocker_class: 'CREDENTIAL_GATED',
    promotion_blocker_class: 'CREDENTIAL_GATED',
    promotion_blocked: true,
    promotion_requirements_complete: false,
    no_go_claim: true,
    credential_names: ['AGENT_ZERO_BASE_URL', 'AGENT_ZERO_API_KEY'],
    credential_values_exposed: false,
    readiness_endpoint: '/api/agent-zero/status',
    read_probe_endpoint: '/api/agent-zero/status',
    status_endpoint: '/api/bridge/agent-zero/status',
    owner_action_type: 'credential',
    audit_state: 'OWNER_GATED',
    rollback_state: 'OWNER_GATED',
    rollback_command: 'disable protected Agent Zero provider route; keep /api/agent-zero/status credential-gated and read-only',
    token_governor_required: true,
    execution_enabled: false,
    writes_enabled: false,
    protected_execution_enabled: false,
    approval_request_created: false,
    audit_record_written: false,
    fake_success_allowed: false,
    go_claim_allowed: false,
  },
  {
    id: 'hermes',
    label: 'Ron Weasley — Nuclear Dispatcher',
    state: 'READY',
    blocker_class: 'NONE',
    promotion_blocker_class: 'NONE',
    promotion_blocked: false,
    promotion_requirements_complete: true,
    no_go_claim: false,
    credential_values_exposed: false,
    readiness_endpoint: '/api/bridge/hermes/full-access/status',
    read_probe_endpoint: '/api/bridge/hermes/system-command-registry',
    status_endpoint: '/api/bridge/hermes/full-access/status',
    owner_action_type: 'jarvis_delegation',
    audit_state: 'READY',
    rollback_state: 'READY',
    rollback_command: 'archive the exact Ron Weasley delegation packet; keep /api/bridge/hermes/execute gated by Jarvis delegation',
    token_governor_required: true,
    execution_enabled: true,
    writes_enabled: true,
    protected_execution_enabled: true,
    approval_request_created: false,
    audit_record_written: true,
    fake_success_allowed: false,
    go_claim_allowed: true,
  },
  {
    id: 'pi',
    label: 'Pi',
    state: 'JARVIS_GATED_FULL_ACCESS',
    blocker_class: 'NONE',
    promotion_blocker_class: 'OWNER_GATED',
    promotion_blocked: true,
    promotion_requirements_complete: true,
    no_go_claim: false,
    credential_values_exposed: false,
    readiness_endpoint: '/api/bridge/pi/status',
    read_probe_endpoint: '/api/bridge/pi/status',
    status_endpoint: '/api/bridge/pi/status',
    capability_matrix_endpoint: '/api/bridge/capability-matrix',
    provider_registry_endpoint: '/api/bridge/providers',
    visible_to_gateway: true,
    visible_to_PI: true,
    visible_to_agent_runtime: true,
    adapter_present: true,
    credential_policy: 'gateway_brokered_names_only_no_secret_values',
    owner_action_type: 'jarvis_delegation',
    audit_state: 'OWNER_GATED',
    rollback_state: 'OWNER_GATED',
    rollback_command: 'disable Pi provider execution routing; keep Pi Gateway reads available and Jarvis-gated',
    token_governor_required: true,
    execution_enabled: true,
    writes_enabled: true,
    protected_execution_enabled: false,
    approval_request_created: false,
    audit_record_written: true,
    fake_success_allowed: false,
    go_claim_allowed: false,
  },
  {
    id: 'paperclip',
    label: 'Paperclip',
    state: 'READ_ONLY',
    blocker_class: 'NONE',
    promotion_blocker_class: 'OWNER_GATED',
    promotion_blocked: true,
    promotion_requirements_complete: false,
    no_go_claim: true,
    credential_values_exposed: false,
    readiness_endpoint: '/api/bridge/paperclip/status',
    read_probe_endpoint: '/api/bridge/paperclip/status',
    status_endpoint: '/api/bridge/paperclip/status',
    owner_action_type: 'owner_approval',
    audit_state: 'OWNER_GATED',
    rollback_state: 'OWNER_GATED',
    rollback_command: 'disable Paperclip provider runner; keep ECO reads available and writes Bridge-gated',
    token_governor_required: true,
    execution_enabled: false,
    writes_enabled: false,
    protected_execution_enabled: false,
    approval_request_created: false,
    audit_record_written: false,
    fake_success_allowed: false,
    go_claim_allowed: false,
  },
  {
    id: 'openclaw-plus',
    label: 'OpenClaw+',
    state: 'SERVICE_DOWN',
    blocker_class: 'SERVICE_DOWN',
    promotion_blocker_class: 'OWNER_GATED',
    promotion_blocked: true,
    promotion_requirements_complete: false,
    no_go_claim: true,
    credential_values_exposed: false,
    readiness_endpoint: '/api/openclaw-plus/status',
    read_probe_endpoint: '/api/openclaw-plus/status',
    status_endpoint: '/api/openclaw-plus/status',
    owner_action_type: 'runtime_proof',
    audit_state: 'OWNER_GATED',
    rollback_state: 'OWNER_GATED',
    rollback_command: 'disable OpenClaw+ provider execution route; keep doctor/runtime status read-only',
    token_governor_required: true,
    execution_enabled: false,
    writes_enabled: false,
    protected_execution_enabled: false,
    approval_request_created: false,
    audit_record_written: false,
    fake_success_allowed: false,
    go_claim_allowed: false,
  },
  {
    id: 'spaceagent',
    label: 'SpaceAgent',
    state: 'JARVIS_GATED_DIRECT_LINE',
    blocker_class: 'NONE',
    promotion_blocker_class: 'OWNER_GATED',
    promotion_blocked: true,
    promotion_requirements_complete: true,
    no_go_claim: false,
    credential_values_exposed: false,
    readiness_endpoint: '/api/bridge/spaceagent/status',
    read_probe_endpoint: '/api/bridge/spaceagent/status',
    status_endpoint: '/api/bridge/spaceagent/status',
    owner_action_type: 'jarvis_delegation',
    audit_state: 'OWNER_GATED',
    rollback_state: 'OWNER_GATED',
    rollback_command: 'disable SpaceAgent provider execution route; keep /api/bridge/spaceagent/status read-only',
    token_governor_required: true,
    execution_enabled: false,
    writes_enabled: false,
    protected_execution_enabled: false,
    approval_request_created: false,
    audit_record_written: true,
    fake_success_allowed: false,
    go_claim_allowed: false,
    visible_to_agent_runtime: true,
  },
] as const
