import { bridgeSessionContract } from '@/lib/bridge-session-contract'
import {
  JARVIS_SCHEDULER_RUN_ACTION,
  JARVIS_SCHEDULER_RUN_ADAPTER_ID,
  JARVIS_SCHEDULER_RUN_TASK_ID,
} from '@/lib/jarvis-scheduler-run-adapter'
import {
  JARVIS_WORKFLOW_RUN_ACTION,
  JARVIS_WORKFLOW_RUN_ADAPTER_ID,
  JARVIS_WORKFLOW_RUN_WORKFLOW_ID,
} from '@/lib/jarvis-workflow-run-adapter'
import {
  JARVIS_REPORT_CREATE_ACTION,
  JARVIS_REPORT_CREATE_ADAPTER_ID,
} from '@/lib/jarvis-report-create-adapter'
import {
  JARVIS_AGENTMAIL_DRAFT_ACTION,
  JARVIS_AGENTMAIL_DRAFT_ADAPTER_ID,
} from '@/lib/jarvis-agentmail-draft-adapter'
import {
  JARVIS_WEBHOOK_LOCAL_PING_ACTION,
  JARVIS_WEBHOOK_LOCAL_PING_ADAPTER_ID,
} from '@/lib/jarvis-webhook-local-ping-adapter'
import {
  JARVIS_OLLAMA_LOCAL_MODEL_ACTION,
  JARVIS_OLLAMA_LOCAL_MODEL_ADAPTER_ID,
  JARVIS_OLLAMA_LOCAL_MODEL_NAME,
} from '@/lib/jarvis-ollama-local-model-adapter'
import {
  JARVIS_BUILDWIKI_RESULT_INGEST_ACTION,
  JARVIS_BUILDWIKI_RESULT_INGEST_ADAPTER_ID,
} from '@/lib/jarvis-buildwiki-result-ingest-adapter'
import {
  JARVIS_DEVELOPER_WORKFLOW_ACTION,
  JARVIS_DEVELOPER_WORKFLOW_ADAPTER_ID,
} from '@/lib/jarvis-developer-workflow-adapter'
import {
  JARVIS_FULL_GO_WORKFLOW_ACTION,
  JARVIS_FULL_GO_WORKFLOW_ADAPTER_ID,
  JARVIS_FULL_GO_WORKFLOW_ID,
} from '@/lib/jarvis-full-go-workflow-adapter'
import {
  JARVIS_TELEGRAM_DELIVERY_ACTION,
  JARVIS_TELEGRAM_DELIVERY_ADAPTER_ID,
} from '@/lib/jarvis-telegram-delivery-adapter'

export type ReadinessHealth =
  | 'healthy'
  | 'read_only'
  | 'degraded'
  | 'credential_gated'
  | 'service_down'
  | 'owner_gated'
  | 'blocked'

export type ExecutionReadinessEntry = {
  id: string
  label: string
  category: 'agent' | 'provider' | 'mcp' | 'brain' | 'connector' | 'tool' | 'report'
  endpoint: string
  visible_to_gateway: boolean
  visible_to_agent_zero: boolean
  visible_to_pi: boolean
  visible_to_runtime: boolean
  read_allowed: boolean
  write_allowed: boolean
  execution_allowed: boolean
  bridge_required: boolean
  adapter_present: boolean
  credential_policy: string
  health: ReadinessHealth
  exact_blocker: string | null
  next_action: string
}

function entry(input: ExecutionReadinessEntry): ExecutionReadinessEntry {
  return input
}

export function buildExecutionReadinessEntries(): ExecutionReadinessEntry[] {
  const bridge = bridgeSessionContract()
  return [
    entry({
      id: 'agent_zero_jarvis',
      label: 'Agent Zero (Jarvis)',
      category: 'agent',
      endpoint: '/api/bridge/agent-zero/status',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'gateway_brokered_no_secret_values',
      health: 'healthy',
      exact_blocker: 'owner_hard_stops_only_remaining',
      next_action: 'Jarvis can execute certified exact-scope adapters through Mission Control. Remaining blocks are owner-hard-stop categories and connectors still needing credentials or adapter proof.',
    }),
    entry({
      id: 'gateway_execution_router',
      label: 'Jarvis Gateway execution router',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'router_metadata_only_no_secret_values',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'Use only exact-scope adapters. The certified first execution action is mcp_readonly_status_probe.',
    }),
    entry({
      id: 'mcp_readonly_status_probe',
      label: 'MCP read-only status probe',
      category: 'mcp',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credential_access_status_probe_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=mcp_readonly_status_probe and exact MCP status-probe scope.',
    }),
    entry({
      id: 'paperclip_eco_task_dry_run',
      label: 'Paperclip ECO task dry-run',
      category: 'connector',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_paperclip_credentials_used_internal_dry_run_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=paperclip_eco_task_dry_run and company=ECO to create an internal rollbackable dry-run record only.',
    }),
    entry({
      id: 'n8n_workflow_list',
      label: 'n8n workflow readiness/list',
      category: 'connector',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'env_name_presence_only_no_secret_values',
      health: 'credential_gated',
      exact_blocker: 'credential_required_if_n8n_api_key_missing',
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=n8n_workflow_list to check n8n readiness and list workflows only when N8N_API_KEY is already present.',
    }),
    entry({
      id: 'buildwiki_run_now',
      label: 'Build-Wiki Run Now dispatch',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_hardcoded_opencloud_docs_farmer_service_only',
      health: 'owner_gated',
      exact_blocker: null,
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=buildwiki_run_now, action=buildwiki.run_now_dispatch, and target=opencloud-docs-farmer.service.',
    }),
    entry({
      id: JARVIS_BUILDWIKI_RESULT_INGEST_ADAPTER_ID,
      label: 'Build-Wiki result ingest',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_redacted_buildwiki_status_audit_metadata_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_BUILDWIKI_RESULT_INGEST_ADAPTER_ID}, action=${JARVIS_BUILDWIKI_RESULT_INGEST_ACTION}, and target=opencloud-docs-farmer.service.`,
    }),
    entry({
      id: JARVIS_SCHEDULER_RUN_ADAPTER_ID,
      label: 'Scheduler auto-backup run-now',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_auto_backup_only_no_raw_paths',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_SCHEDULER_RUN_ADAPTER_ID}, action=${JARVIS_SCHEDULER_RUN_ACTION}, and task_id=${JARVIS_SCHEDULER_RUN_TASK_ID}.`,
    }),
    entry({
      id: JARVIS_WORKFLOW_RUN_ADAPTER_ID,
      label: 'Jarvis daily health workflow run',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_daily_health_snapshot_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_WORKFLOW_RUN_ADAPTER_ID}, action=${JARVIS_WORKFLOW_RUN_ACTION}, and workflow_id=${JARVIS_WORKFLOW_RUN_WORKFLOW_ID}.`,
    }),
    entry({
      id: JARVIS_REPORT_CREATE_ADAPTER_ID,
      label: 'Agent Zero internal report create',
      category: 'report',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_report_artifacts_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_REPORT_CREATE_ADAPTER_ID}, action=${JARVIS_REPORT_CREATE_ACTION}, and target=internal_report.`,
    }),
    entry({
      id: JARVIS_AGENTMAIL_DRAFT_ADAPTER_ID,
      label: 'AgentMail internal draft create',
      category: 'connector',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_draft_only_no_send',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_AGENTMAIL_DRAFT_ADAPTER_ID}, action=${JARVIS_AGENTMAIL_DRAFT_ACTION}, and target=internal_draft.`,
    }),
    entry({
      id: JARVIS_WEBHOOK_LOCAL_PING_ADAPTER_ID,
      label: 'Webhook local ping',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_local_ping_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_WEBHOOK_LOCAL_PING_ADAPTER_ID}, action=${JARVIS_WEBHOOK_LOCAL_PING_ACTION}, and target=mission_control_internal_ping.`,
    }),
    entry({
      id: 'paperclip_eco_task_write',
      label: 'Paperclip ECO issue comment write',
      category: 'connector',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'paperclip_api_key_required_by_name_only_no_value_exposure',
      health: 'owner_gated',
      exact_blocker: 'paperclip_write_credential_required_if_api_key_missing',
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=paperclip_eco_task_write, action=paperclip.eco_issue_comment.create, scope company=ECO operation=issue_comment_create target=existing_issue, and a safe ECO issue identifier.',
    }),
    entry({
      id: 'mcp_memory_write_probe',
      label: 'MCP memory write-capable probe',
      category: 'mcp',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'local_mcp_memory_server_no_secret_values_isolated_proof_graph',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'POST /api/bridge/agent-zero/execute with adapter_id=mcp_memory_write_probe and exact memory create/delete scope. No arbitrary MCP tools are enabled.',
    }),
    entry({
      id: 'provider_model_execution',
      label: 'Provider/model execution',
      category: 'provider',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: false,
      credential_policy: 'gateway_brokered_cost_governed_no_raw_keys',
      health: 'blocked',
      exact_blocker: 'token_governor_not_proven',
      next_action: 'Keep provider/model execution disabled until Token Governor runtime enforcement is proven.',
    }),
    entry({
      id: JARVIS_OLLAMA_LOCAL_MODEL_ADAPTER_ID,
      label: 'Gateway Ollama local model execute',
      category: 'provider',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'local_ollama_only_no_secret_values_zero_cost_governed',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_OLLAMA_LOCAL_MODEL_ADAPTER_ID}, action=${JARVIS_OLLAMA_LOCAL_MODEL_ACTION}, and model=${JARVIS_OLLAMA_LOCAL_MODEL_NAME}.`,
    }),
    entry({
      id: 'pi_gateway_agent',
      label: 'Pi',
      category: 'agent',
      endpoint: '/api/bridge/pi/status',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'gateway_brokered_names_only_no_secret_values',
      health: 'healthy',
      exact_blocker: 'production_execution_requires_jarvis_concurrence',
      next_action: 'Pi has direct Gateway pipeline access to tools, skills, MCPs, providers, Brain reads, visible task events, and pipeline requests; production-impacting execution remains Jarvis-gated.',
    }),
    entry({
      id: 'provider_registry',
      label: 'Provider registry',
      category: 'provider',
      endpoint: '/api/bridge/providers',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'names_only_no_secret_values',
      health: 'degraded',
      exact_blocker: 'providers_mixed_health',
      next_action: 'Repair credential-gated and service-down providers before offering execution.',
    }),
    entry({
      id: 'mcp_registry',
      label: 'MCP registry',
      category: 'mcp',
      endpoint: '/api/bridge/mcp-readiness',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_direct_secret_access',
      health: 'degraded',
      exact_blocker: 'mcp_servers_mixed_health',
      next_action: 'Repair failed/degraded MCP servers; tool invocation stays Bridge-gated.',
    }),
    entry({
      id: 'integration_search',
      label: 'Integration search',
      category: 'tool',
      endpoint: '/api/bridge/integration-hardening',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'read_only_inventory_no_secret_values',
      health: 'read_only',
      exact_blocker: 'execution_requires_bridge_session',
      next_action: 'Use the route for visibility only until execution adapters are approved and audited.',
    }),
    entry({
      id: 'brain_readiness',
      label: 'Brain / Memory readiness',
      category: 'brain',
      endpoint: '/api/bridge/brain-readiness',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'write_scope_requires_owner_approval',
      health: 'owner_gated',
      exact_blocker: 'brain_write_sync_requires_bridge_and_backend_proof',
      next_action: 'Keep reads visible; prove Obsidian/MemPalace/Brain write adapters under Bridge before enabling writes.',
    }),
    entry({
      id: 'obsidian',
      label: 'Obsidian',
      category: 'brain',
      endpoint: '/api/bridge/brain-readiness',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'canonical_vault_only_no_raw_paths',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'Use /api/bridge/agent-zero/execute with adapter_id=obsidian_write, action=obsidian.note.create, and scope system=obsidian operation=create_note vault=canonical.',
    }),
    entry({
      id: 'obsidian_structured_project_note_write',
      label: 'Obsidian Structured Project Notes',
      category: 'brain',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'canonical_vault_controlled_folder_only_no_raw_paths',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'Use /api/bridge/agent-zero/execute with adapter_id=obsidian_structured_project_note_write, action=obsidian.note.structured_project_create, and scope system=obsidian operation=structured_project_note_create vault=canonical folder=jarvis_full_go.',
    }),
    entry({
      id: 'mempalace',
      label: 'MemPalace',
      category: 'brain',
      endpoint: '/api/bridge/brain-readiness',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'safe_memory_summary_only_no_raw_dump',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'Use /api/bridge/agent-zero/execute with adapter_id=mempalace_write, action=mempalace.memory.remember_owner_preference, and scope system=mempalace operation=remember_owner_preference vault=safe_memory_summary.',
    }),
    entry({
      id: 'mempalace_categorized_memory_write',
      label: 'MemPalace Categorized Task Memory',
      category: 'brain',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'safe_memory_summary_task_result_only_no_raw_dump',
      health: 'healthy',
      exact_blocker: null,
      next_action: 'Use /api/bridge/agent-zero/execute with adapter_id=mempalace_categorized_memory_write, action=mempalace.memory.categorized_summary_write, and scope system=mempalace operation=categorized_memory_write vault=safe_memory_summary category=task_result.',
    }),
    entry({
      id: 'paperclip',
      label: 'Paperclip ECO',
      category: 'connector',
      endpoint: '/api/bridge/paperclip/status',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'paperclip_login_required_no_password_storage',
      health: 'healthy',
      exact_blocker: 'paperclip_writes_bridge_gated',
      next_action: 'Use ECO read-only; task writes remain Bridge-gated.',
    }),
    entry({
      id: 'report_preview',
      label: 'Jarvis report preview',
      category: 'report',
      endpoint: '/api/bridge/agent-zero/reports',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: false,
      adapter_present: true,
      credential_policy: 'no_secret_values_no_raw_paths',
      health: 'read_only',
      exact_blocker: null,
      next_action: 'Allow preview generation; require Bridge for send/upload/delivery.',
    }),
    entry({
      id: 'jarvis_authority',
      label: 'Jarvis authority matrix',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/authority',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: false,
      adapter_present: true,
      credential_policy: 'policy_metadata_only_no_secret_values',
      health: 'read_only',
      exact_blocker: null,
      next_action: 'Use this route to classify Jarvis actions before offering execution or write controls.',
    }),
    entry({
      id: 'jarvis_internal_write',
      label: 'Jarvis internal Mission Control writes',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/internal-write',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: false,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: bridge.internal_writes_enabled,
      execution_allowed: false,
      bridge_required: !bridge.internal_writes_enabled,
      adapter_present: true,
      credential_policy: 'mission_control_state_only_no_external_writes',
      health: bridge.internal_writes_enabled ? 'healthy' : 'owner_gated',
      exact_blocker: bridge.internal_writes_enabled ? null : 'bridge_session_required',
      next_action: bridge.internal_writes_enabled
        ? 'Internal Mission Control records can be written by Jarvis with audit and rollback metadata; external writes remain gated.'
        : 'Create or renew the Jarvis owner-operator session before internal Mission Control writes.',
    }),
    entry({
      id: 'jarvis_adapter_registry',
      label: 'Jarvis exact-scope adapter registry',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/authority',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'adapter_schema_only_secret_values_never_returned',
      health: 'owner_gated',
      exact_blocker: 'exact_scope_adapter_approval_required',
      next_action: 'Use dry-run and approval requests before any external connector, provider, brain, Paperclip, or Build-Wiki action.',
    }),
    entry({
      id: 'jarvis_workflows',
      label: 'Jarvis workflow registry',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/workflows',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: bridge.internal_writes_enabled,
      execution_allowed: false,
      bridge_required: !bridge.internal_writes_enabled,
      adapter_present: true,
      credential_policy: 'workflow_records_only_no_connector_execution',
      health: bridge.internal_writes_enabled ? 'healthy' : 'owner_gated',
      exact_blocker: bridge.internal_writes_enabled ? null : 'bridge_session_required',
      next_action: bridge.internal_writes_enabled
        ? 'Jarvis can queue internal workflow records; workflow execution still requires exact-scope adapters.'
        : 'Create or renew the Jarvis owner-operator session before queuing workflow records.',
    }),

    entry({
      id: JARVIS_DEVELOPER_WORKFLOW_ADAPTER_ID,
      label: 'Jarvis controlled developer workflow change request',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_change_request_only_no_source_mutation',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_DEVELOPER_WORKFLOW_ADAPTER_ID}, action=${JARVIS_DEVELOPER_WORKFLOW_ACTION}, and target=source_controlled_surface.`,
    }),
    entry({
      id: JARVIS_FULL_GO_WORKFLOW_ADAPTER_ID,
      label: 'Jarvis Full GO bounded ECO workflow',
      category: 'tool',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'no_credentials_required_internal_workflow_record_only',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_FULL_GO_WORKFLOW_ADAPTER_ID}, action=${JARVIS_FULL_GO_WORKFLOW_ACTION}, workflow_id=${JARVIS_FULL_GO_WORKFLOW_ID}, and company=ECO.`,
    }),
    entry({
      id: JARVIS_TELEGRAM_DELIVERY_ADAPTER_ID,
      label: 'Telegram exact owner allowlist send',
      category: 'connector',
      endpoint: '/api/bridge/agent-zero/execute',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: true,
      read_allowed: true,
      write_allowed: true,
      execution_allowed: true,
      bridge_required: true,
      adapter_present: true,
      credential_policy: 'brokered_owner_allowlist_no_token_or_chat_id_exposure',
      health: 'healthy',
      exact_blocker: null,
      next_action: `POST /api/bridge/agent-zero/execute with adapter_id=${JARVIS_TELEGRAM_DELIVERY_ADAPTER_ID}, action=${JARVIS_TELEGRAM_DELIVERY_ACTION}, and target=owner_chat.`,
    }),
    entry({
      id: 'jarvis_certification',
      label: 'Jarvis owner-operator certification',
      category: 'report',
      endpoint: '/api/bridge/agent-zero/certification',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: false,
      adapter_present: true,
      credential_policy: 'certification_metadata_only_no_secret_values',
      health: 'read_only',
      exact_blocker: null,
      next_action: 'Exact-scope MCP read-only status probe is now the first execution-capable proof; broader protected execution remains gated.',
    }),
    entry({
      id: 'report_delivery',
      label: 'Jarvis report send/delivery',
      category: 'report',
      endpoint: '/api/bridge/agent-zero/reports',
      visible_to_gateway: true,
      visible_to_agent_zero: true,
      visible_to_pi: true,
      visible_to_runtime: false,
      read_allowed: true,
      write_allowed: false,
      execution_allowed: false,
      bridge_required: true,
      adapter_present: false,
      credential_policy: 'delivery_credentials_required_through_secret_path',
      health: 'owner_gated',
      exact_blocker: 'bridge_session_required',
      next_action: 'Send/upload requires Bridge Session, delivery adapter proof, audit, and rollback.',
    }),
  ]
}

export function buildExecutionReadinessMatrix() {
  const entries = buildExecutionReadinessEntries()
  const bridge = bridgeSessionContract()
  return {
    generated_at: new Date().toISOString(),
    contract_version: 'jarvis-access-v1',
    bridge_session: bridge,
    entries,
    summary: {
      total: entries.length,
      visible_to_gateway: entries.filter((item) => item.visible_to_gateway).length,
      visible_to_agent_zero: entries.filter((item) => item.visible_to_agent_zero).length,
      visible_to_pi: entries.filter((item) => item.visible_to_pi).length,
      visible_to_runtime: entries.filter((item) => item.visible_to_runtime).length,
      read_allowed: entries.filter((item) => item.read_allowed).length,
      write_allowed: entries.filter((item) => item.write_allowed).length,
      execution_allowed: entries.filter((item) => item.execution_allowed).length,
      bridge_required: entries.filter((item) => item.bridge_required).length,
      adapter_present: entries.filter((item) => item.adapter_present).length,
      blocked_or_gated: entries.filter((item) => item.exact_blocker).length,
    },
    repair_queues: {
      credential_or_owner_gated: entries.filter((item) =>
        item.health === 'credential_gated' || item.health === 'owner_gated',
      ).map((item) => item.id),
      service_or_adapter_missing: entries.filter((item) =>
        item.health === 'service_down' || !item.adapter_present,
      ).map((item) => item.id),
      degraded_or_blocked: entries.filter((item) =>
        item.health === 'degraded' || item.health === 'blocked',
      ).map((item) => item.id),
    },
  }
}
