import { NextRequest, NextResponse } from 'next/server'
import { requireRole } from '@/lib/auth'

export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

const APPROVAL_CONTRACT = [
  {
    connector: 'bridge',
    action: 'agent_to_agent_execution',
    category: 'agent_execution',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Agent-to-agent execution is disabled until approval persistence, audit chain, and rollback pointers exist.',
  },
  {
    connector: 'brain_sync',
    action: 'memory_write',
    category: 'memory',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Protected memory cannot be overwritten automatically.',
  },
  {
    connector: 'harness',
    action: 'route_or_handoff',
    category: 'routing',
    risk_level: 'medium',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Production handoffs and route changes need scoped approval and audit persistence.',
  },
  {
    connector: 'zapier',
    action: 'write_tool_invocation',
    category: 'external_automation',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Zapier writes can mutate external systems and must remain locked.',
  },
  {
    connector: 'zapier',
    action: 'tool_list',
    category: 'external_automation',
    risk_level: 'low',
    required_approval: false,
    audit_required: false,
    current_state: 'READ_ONLY',
    http_status_when_blocked: null,
    reason: 'Read-only tool discovery is allowed when credentials are configured.',
  },
  {
    connector: 'n8n',
    action: 'workflow_execute_or_toggle',
    category: 'external_automation',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Workflow activation/execution can trigger external actions.',
  },
  {
    connector: 'firecrawl',
    action: 'credentialed_crawl_or_memory_ingest',
    category: 'research',
    risk_level: 'medium',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Credentialed crawl and memory ingest require scoped approval.',
  },
  {
    connector: 'viral_crawl_video',
    action: 'run_video_wrapper_or_write_obsidian',
    category: 'research',
    risk_level: 'medium',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Video Intelligence can download/process external media and write notes into Obsidian, so UI execution stays locked until approval persistence, audit chain, and a safe runner exist.',
  },
  {
    connector: 'mcp',
    action: 'enable_disable_reauth',
    category: 'tooling',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'MCP config changes alter available tools and auth posture.',
  },
  {
    connector: 'mcp',
    action: 'tool_invocation',
    category: 'tooling',
    risk_level: 'medium',
    required_approval: true,
    audit_required: true,
    current_state: 'BACKEND_REQUIRED',
    http_status_when_blocked: 503,
    reason: 'Per-tool read/write classification and runner are not implemented.',
  },
  {
    connector: 'skills',
    action: 'install_enable_disable',
    category: 'skills',
    risk_level: 'medium',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Skill changes alter agent capabilities.',
  },
  {
    connector: 'models',
    action: 'route_change',
    category: 'model_routing',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Model/provider routing changes can affect cost, behavior, and safety.',
  },
  {
    connector: 'system',
    action: 'credentials_firewall_caddy_cloudflare_docker',
    category: 'infrastructure',
    risk_level: 'high',
    required_approval: true,
    audit_required: true,
    current_state: 'OWNER_APPROVAL_REQUIRED',
    http_status_when_blocked: 423,
    reason: 'Infrastructure/security changes require explicit owner approval.',
  },
]

export async function GET(request: NextRequest) {
  const auth = requireRole(request, 'viewer')
  if ('error' in auth) return NextResponse.json({ error: auth.error }, { status: auth.status })

  return NextResponse.json({
    ok: true,
    mode: 'read_only_contract',
    generated_at: new Date().toISOString(),
    protected_writes_default: 'OWNER_APPROVAL_REQUIRED',
    enforcement: {
      protected_write_http_status: 423,
      no_fake_success: true,
      no_execution_enabled: true,
      db_persistence: 'draft_only_not_applied',
    },
    approvals: APPROVAL_CONTRACT,
    summary: {
      total: APPROVAL_CONTRACT.length,
      owner_approval_required: APPROVAL_CONTRACT.filter((item) => item.required_approval).length,
      read_only_allowed: APPROVAL_CONTRACT.filter((item) => item.current_state === 'READ_ONLY').length,
    },
  })
}
